# .github/workflows/ci.yml
name: CI - Processing 4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Core-Utils
      run: |
        sudo apt-get update
        sudo apt-get install -y coreutils
        export PATH=$PATH:/usr/bin
          
    - name: Install Snapd
      run: |
        sudo apt update
        sudo apt install -y snapd
        sudo systemctl start snapd
        sudo systemctl enable snapd

    - name: Install Processing 4 using Snap
      run: |
        sudo snap install processing --classic
        # Confirm installation
        processing --version

    - name: Run Processing sketch
      run: |
        processing-java --sketch=$(pwd)/sketch --run
